# Catch Exceptions
## Multiple Catches
* Use multiple ```catch``` to only catch the specific ```Exception``` and its subclasses
    ```java
    public static void main(String[] args) {
        try {
            process1();
            process2();
            process3();
        } catch (IOException e) {
            System.out.println(e);
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
    } 
    ```
* When there are multiple ```catch```, the order of the catch is very important: the subclasses must be the firsts
    ```java
    public static void main(String[] args) {
        try {
            process1();
            process2();
            process3();
        } catch (IOException e) {
            System.out.println("IO error");
        } catch (UnsupportedEncodingException e) { // 永远捕获不到
            System.out.println("Bad encoding");
        }
    }
    ```
* The second exception can never be caught because it's the subclass of ```IOExceiption```
---
## Finally
* Whether or not the exception happens, we still want some code to work. In this case, we use the ```finally```
    ```java
    public static void main(String[] args) {
        try {
            process1();
            process2();
            process3();
        } catch (UnsupportedEncodingException e) {
            System.out.println("Bad encoding");
        } catch (IOException e) {
            System.out.println("IO error");
        } finally {
            System.out.println("END");
        }
    }
    ```
1. ```finally``` is optional
2. ```finally``` will always execute at the end

* In some cases, you can use only ```try...finally``` without the catch part when you throw the exceptions when defining the methods

## Catch Multiple Exceptions
* If there are multiple exceptions sharing the same solutions, and the exceptions don't herite each other, you need to write multiple ```catch```
    ```java
    public static void main(String[] args) {
        try {
            process1();
            process2();
            process3();
        } catch (IOException e) {
            System.out.println("Bad input");
        } catch (NumberFormatException e) {
            System.out.println("Bad input");
        } catch (Exception e) {
            System.out.println("Unknown error");
        }
    }
    ```
* Since the code to handle ```IOException``` and ```NumberFormatException``` is the same, you can use ```|``` to merge them
    ```java
    catch (IOException | NumberFormatException e)
    ```
